// <auto-generated />
using DeliveryService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DeliveryService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DeliveryService.Entities.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Delivery_Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery_ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Delivery_charge")
                        .HasColumnType("int");

                    b.Property<string>("Delivery_location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Deliveries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Delivery_Contact = "0765645123",
                            Delivery_ProductName = "Hanging Wall Art",
                            Delivery_charge = 250,
                            Delivery_location = "Matale",
                            OrderID = 3
                        },
                        new
                        {
                            Id = 2,
                            Delivery_Contact = "0765645444",
                            Delivery_ProductName = "Painting Decoration Wall Art",
                            Delivery_charge = 300,
                            Delivery_location = "Kandy",
                            OrderID = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
